name: Run Arxiv Papers Daily

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 */12 * * *"  # every 12 hours

env:
  GITHUB_USER_NAME: mahdims
  GITHUB_USER_EMAIL: mahdi.ms86@gmail.com

jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python Env
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily arxiv
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python daily_arxiv.py

      - name: Commit and push updates
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Github Action Automatic Update LLM Arxiv Papers"
          files: README.md docs/or-llm-daily.json docs/or-llm-daily-web.json docs/index.md docs/relevance_cache.json
          rebase: 'true'
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
