name: Run Update Paper Links Weekly

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 8 * * 1"  # At 08:00 on Monday

permissions:
  contents: write

env:
  GITHUB_USER_NAME: mahdims
  GITHUB_USER_EMAIL: mahdi.ms86@gmail.com

jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python Env
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update paper links
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python daily_arxiv.py --update_paper_links

      - name: Commit and push updates
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Github Action Automatic Update Paper Links"
          files: README.md docs/or-llm-daily.json docs/or-llm-daily-web.json docs/index.md docs/relevance_cache.json
          rebase: 'true'
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
